version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
